### ISSUE TITLE
Actividad - multiplicación de matrices con threads

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2523-2018-2/syllabus#1]
Hola! En el caso de la multiplicación con threads, ¿qué es lo más recomendable, que la operación de multiplicar un vector fila por un vector columna sea hecho por un thread (n × n threads) o que cada thread se encargue de una fila o columna, etc? 

Muchas gracias
Saludos

**Comment by gpvidal** [comment]
Hola @AlfonsoIgnacioV !

Es una excelente pregunta! Y no es tan fácil de responder! Pero lo más simple: La que resulte más rápida.

Ahora ¿Por qué no es tán fácil de responder? Porque existe el problema de "Heterogeneidad". Puedes correrlo en tu computador de forma óptima con una N cantidad de *threads*, que podría ser no óptima en otro sistema.

En general lo que haces, es que puedes indicar la cantidad de *threads* máximos a ejecutar. ¿Por qué pasa esto? Imagínate si lanzas muchos *threads* juntos ¿Podría "colapsar" el procesador?

Por eso, sólo te quedará probar para ver cuál es mejor :wink: 

Saludos,
Gabriel
