### ISSUE TITLE
Acceso plataforma

### ISSUE THREAD

**Issue by Hernan4444** [IIC2523-2018-2/syllabus#10]
Hola, 
Tal como dice en el enunciado, uno tenía que pedir por el foro acceso a la plataforma con `Ubuntu 18.04 (bionic)`, así que aquí lo estoy haciendo 😅.

Saludos ✌️

**Comment by farojos** [comment]
Lo tendremos ASAP.

Saludos

**Comment by gpvidal** [comment]
Hola @Hernan4444 ,

Estoy realizando las últimas pruebas de acceso y de funcionamiento. Hoy, durante la tarde/noche, te hago llegar las credenciales.

Saludos,
Gabriel

**Comment by gpvidal** [comment]
Hola @Hernan4444 

Es posible que, vía email, me envies una llave pública para darte acceso? Si necesitas instrucciones puedes revisar:

https://confluence.atlassian.com/bitbucketserver/creating-ssh-keys-776639788.html

Saludos,

**Comment by AlfonsoIgnacioV** [comment]
Hola!
También quisiera solicitar acceso, por favor. Me acabo de crear una llave también
Saludos! :)
