### ISSUE TITLE
Debugging Tarea 2 Memory Leaf

### ISSUE THREAD

**Issue by Hernan4444** [IIC2523-2018-2/syllabus#11]
Hola, 

En la ayudantía se nos indicó que los *memory leak* serían un motivo de penalización. He intentado correr Valgrind con el programa más sencillo (hello world) pero ya me salen varios *memory leak* e incluso malloc que no han sido liberados, por lo tanto puedo suponer que no estoy implementando correctamente Valgrind dentro de MPI, pero no sé si son errores de mi código o de MPI.

¿Es posible darnos una guía de como poder debuggear con Valgrind o cualquier otra herramienta, el ejecutable creado con MPI para verificar esa clase de errores? o tal vez el otro viernes una pequeña ayudantía que expliquen como debuggear con MPI 🙈 

Saludos ✌️

**Comment by farojos** [comment]
Valgrind arroja falsos positivos al analizar código con MPI: https://stackoverflow.com/questions/8471773/mpi-memory-leak. 

Te recomiendo analizar tu codigo sin MPI y verificar que esto no tenga leaks.

Saludos
