### ISSUE TITLE
Temática de la presentación

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2523-2018-2/syllabus#12]
Hola! Escribo para preguntar acerca de la temática de la presentación, ya que en mi caso es _Multithreading Synchronization_ y esta materia la vimos en sistemas operativos. 

1. ¿En este caso está bien si se habla resumidamente de lo que se vio entonces y ahora se habla con más énfasis en algo relacionado? (Por ejemplo, como funciona esto por hardware y software). 

2. Dado que la presentación es en el contexto del ramo, ¿qué tanta importancia se le da a que lo relacionemos con el tema de sistemas distribuidos? (Puede parecer un poco obvia la pregunta, pero me da la impresión que esta relación no se mide de forma explícita en la pauta de evaluación)

Muchas gracias!
Saludos

**Comment by gpvidal** [comment]
Hola @AlfonsoIgnacioV ,

Debes considerar que no todos tus compañeros han hecho el curso de sistemas operativos, por lo que sí sería ideal que puedas resumirlo o indicar las cosas más relevantes.

Con respecto a la pregunta sobre el contexto, todos los temas tienen que ver con sistemas distribuidos. De hecho, en tu caso, vas a distribuir operaciones en 2 o más threads :wink: 

Saludos,

**Comment by AlfonsoIgnacioV** [comment]
Ok! Muchas gracias :)
Saludos

**Comment by AlfonsoIgnacioV** [comment]
Hola! Tal vez sea un poco obvio, pero nunca está de más preguntar. ¿En el caso de la calidad del material que dejamos a nuestros compañeros, qué se espera exactamente? ¿Es un criterio suficiente el considerar que lo que se dijo en la presentación esté explicado con nuestras palabras?

Muchas gracias!
Saludos :)

**Comment by gpvidal** [comment]
Hola @AlfonsoIgnacioV ,

Puede ser las mismas diapositivas o material adicional. Lo importante es que esté claramente el objetivo de la tecnología, qué problemas soluciona, y finalmente que permita responder alguna pregunta que podría estar en la interrogación.

Si la tecnologia soluciona varios problemas, ideal que también estén detallados.

Saludos,

**Comment by AlfonsoIgnacioV** [comment]
Gracias profesor!
Saludos :)
