### ISSUE TITLE
Tarea 2 - Nodo con archivo de lectura y construcción de programa

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2523-2018-2/syllabus#15]
Hola! tengo algunas dudas respecto a la tarea:

1. ¿Qué nodo tiene el archivo que contiene la secuencia de ADN? ¿Es necesario que sólo un nodo tenga el archivo (por ejemplo podría ser el nodo "maestro" o nodo 0, en cuyo caso puede mandar una fracción), o por el contrario, es necesario que todos lo tengan? 

2. ¿A qué se refiere el enunciado con "construcción del programa"? (Asumiendo que no se usa una _makefile_)

Muchas gracias!
Saludos :)

**Comment by farojos** [comment]
1.- Tal como se mencionó en la ayudantía, pueden asumir que el home se encuentra compartido entre los nodos.

2.- Debes mencionar como correr tu programa considerando que solo debes subir el código y no su versión compilada(es decir, debes explicar como compilar y ejecutar tu programa) 

Saludos
