### ISSUE TITLE
Comunicación Indirecta - diagrama de su implementación

### ISSUE THREAD

**Issue by Hernan4444** [IIC2523-2018-2/syllabus#16]
Hola ,

¿Es posible compartir algún link o foto de un diagrama de implementación? Esto es para tener una orientación de que es lo esperado en este tipo de diagrama. 

Saludos ✌️

**Comment by gpvidal** [comment]
Hola @Hernan4444 !

No entiendo tu pregunta, están publicados los diagramas de:

- Publish/Subscribe
- Memoria compartida
- Espacios de tuplas

¿Qué faltaría?

Saludos,
Gabriel

**Comment by Hernan4444** [comment]
@gpvidal lo que pasa es que cuando vi el diagrama de comunicación de grupos, eran distintos a los demás
* imagen 1:
![imagen 1](https://user-images.githubusercontent.com/15641721/48419911-e110eb00-e737-11e8-8a07-3d778569ee4e.png)

* imagen 2:
![imagen 2](https://user-images.githubusercontent.com/15641721/48419931-eb32e980-e737-11e8-89b1-6f631706a74d.png)

Y por ello me empezó a confundir que es lo que buscaba representar este tipo de diagrama, ¿las entidades?, ¿el protocolo de administración (como la imagen 1) de algún modelo?. 
Puede ser que los otros estaba bien genéricos y por ello no lograba aplicarlos para la actividad opcional. Por eso buscaba un ejemplo más aplicado a un caso real para poder entender bien cuales son las cosas a enfatizar en este tipo de diagrama.

**Comment by gpvidal** [comment]
@Hernan4444 entiendo, lo que pasa es que los grupos los ejemplificamos con un chat, por eso no había imagen para eso.

Con respecto a publish/subscribe puedes ver un ejemplo [aquí](https://www.rabbitmq.com/tutorials/tutorial-three-python.html). Es un ejemplo obtenido de la documentación de RabbitMQ (de la cual nadie quiso presentar :disappointed: ).

Avísame si te quedan más dudas.

Saludos,
