### ISSUE TITLE
T03 - Tiempo de ejecución

### ISSUE THREAD

**Issue by Hernan4444** [IIC2523-2018-2/syllabus#17]
Hola, en el enunciado se especifica:

> Para cada uno de los algoritmos debes hacer 15 simulaciones que involucren 10 ejecuciones del algoritmo. Debe haber un tiempo (1 o 2 minutos) entre las ejecuciones.

No entiendo bien ese punto,
1. Si hay 15 simulaciones que involucren 10 ejecuciones, ¿Qué pasa en las otras 5 simulaciones?
2. ¿A qué se refiere con un tiempo entre ejecuciones? Se me ocurre que es el tiempo entre cada simulación o el tiempo tomado en enviar la respuesta luego que un reloj recibe la señal de mandar su hora, pero prefiero confirmar si es alguno de estos o ninguno 😅.

Disculpen si las dudas son básicas, pero prefiero preguntar de todos modos 😄 
Gracias de antemano :v:

**Comment by gpvidal** [comment]
Hola @Hernan4444 ,

No hay problema, yo prefiero que pregunten en todo caso :+1: :

Este es el esquema que deberían seguir:

```
| Ejecución 1 | 1 o 2 min | Ejecución 2 | 1 o 2 min | Ejecución 3 | ... | Ejecución 10 |
| ------------------------------------ Simulación 1 ---------------------------------- |
```
Si tienes dudas nos las envías :wink: 

Saludos,
Gabriel
