### ISSUE TITLE
T03 - Salida del programa

### ISSUE THREAD

**Issue by aiquinones** [IIC2523-2018-2/syllabus#18]
Hola, tengo algunas dudas sobre la salida del programa.

* Hasta ahora, estoy haciendo dos programas distintos, uno para Cristian y otro para NTP. Esto está bien, o es necesario que los outputs estén juntos?

* El output tiene que ser en consola? o se deben escribir el output en un archivo `output.txt`?

```
***********************************
* Algoritmo de Cristian
***********************************
 
Reloj inicial:
Reloj sistema 1: 12345
Reloj sistema 2: 75434
 
Simulación 1:
Reloj sistema 1: 3456789
Reloj sistema 2: 5678906
Diferencia: 4556
 
Simulación 2:
Reloj sistema 1: 3454789
Reloj sistema 2: 5674906
Diferencia: 6556
 
[...]
 
***********************************
* Mi algoritmo NTP
***********************************
 
[...]
```

* Cuál es la estructura del output? Hasta el momento entiendo que, entrego el **tiempo inicial** de los relojes,  sus **tiempos finales**, y además de una **Diferencia = diferencia promedio** durante las 10 ejecuciones de cada simulación. Esta es la duda principal, porque estoy adivinando cuál es la estructura del output.

Gracias!

**Comment by gpvidal** [comment]
Hola @Aiquinones ,

> Hasta ahora, estoy haciendo dos programas distintos, uno para Cristian y otro para NTP. Esto está bien, o es necesario que los outputs estén juntos?

Sí, se puede hacer. Recuerda incluirlo en el archivo en donde le explicas al ayudante como correr tu tarea.

 > El output tiene que ser en consola? o se deben escribir el output en un archivo output.txt?

En consola basta.

> Cuál es la estructura del output? Hasta el momento entiendo que, entrego el tiempo inicial de los relojes, sus tiempos finales, y además de una Diferencia = diferencia promedio durante las 10 ejecuciones de cada simulación. Esta es la duda principal, porque estoy adivinando cuál es la estructura del output.

La estructura es: 
* Nombre del algoritmo
* Relo inicial con el que parten ambos
* Para cada simulación:
  * Número de simulación
  * Los últimos relojes de la simulación
  * Diferencia entre ambos relojes 

> Esta es la duda principal, porque estoy adivinando cuál es la estructura del output.

La idea es que si algo no está claro puedan preguntar, no adivinar :+1: 

Saludos,
Gabriel

**Comment by Hernan4444** [comment]
Hola, 
La duda que tengo es con las ejecuciones.
Son 10 ejecuciones por simulación, pero es 

Sincronizo, espero 1 a  2 minutos, vuelvo a sincronizar, espero 1 a 2 minutos, .... , luego de hacer eso 10 veces, veo la diferencia de los relojes. ¿Eso? 

Saludos

**Comment by gpvidal** [comment]
Hola @Hernan4444 ,

Sí, efectivamente :+1: 

Saludos,

**Comment by benjavides** [comment]
Las simulaciones son secuenciales o independientes? Quiero decir: La simulación 2 parte del estado final de la simulación 1 o reseteamos los relojes al estado inicial?

**Comment by gpvidal** [comment]
Hola @benjavides ,

Independientes.

Saludos,
Gabriel

**Comment by aiquinones** [comment]
Gracias @gpvidal !

Solo para aclarar:
Si mi reloj 1 es 3456789 al terminar la simulación y reloj 2 es 5678906, entonces **Diferencia** es 5678906-3456789=2222117

Correcto?

**Comment by gpvidal** [comment]
@Aiquinones Sí, correcto! De hecho podrías hacer algo de este estilo:

| 5678906 - 3456789 | = 2222117

Recuerda agregar o indicar en qué unidad está expresada tu diferencia (en el readme o en la salida) :+1:

**Comment by AntoniaMendoza** [comment]
Sobre esto, entonces todas las simulaciones tienen el mismo valor inicial de reloj 1 y reloj 2? 
Le ponemos el valor que queramos que cumpla que tienen un dia de diferencia nomás?

**Comment by gpvidal** [comment]
@AntoniaMendoza Puedes indicarlo en el readme.

Saludos,
