### ISSUE TITLE
[Examen] ¿Se podría subir una guía de ejercicios?

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2523-2018-2/syllabus#19]
Hola profesor: Escribo esta issue para pedir, si fuera posible, que por favor se suba una guía con ejercicios, algo similar al ejercicio que se propuso para estudiar para la I2. Pienso que esto podría ayudar mucho a entender realmente qué es lo que se espera, por ejemplo, a nivel comparativo de cosas que mostraron nuestros compañeros (preguntas del tipo: ¿Qué es mejor usar para tal problema, blockchain o TITAN? por decir algo), o también de otras cosas que se vieron. Creo que también eso hace que el estudio sea mucho más efectivo que solamente leerse la materia (considerando también que el examen es con apuntes).

Muchas gracias
Saludos cordiales :)

**Comment by gpvidal** [comment]
Hola @AlfonsoIgnacioV ,

La verdad es que, dado que ya tengo el examen listo, prefiero no realizar esta guía por la simple razón que puedo hacerles una que toque/no toque los temas del examen (bias). Después, finalmente sería mi responsabilidad hacerles estudiar algo que entra/no entra.

Sin embargo, voy a estar este miércoles (en el horario de clases) respondiendo dudas a aquellos que lleguen a la sala. Si necesitan otra instancia podemos hacerlo durante los horarios de clases (aunque ya no hayan).

De todas formas, siempre está este medio para que hagan todas las preguntas que necesiten.

Saludos,

**Comment by AlfonsoIgnacioV** [comment]
Ok!
Muchas gracias
Saludos :)
