### ISSUE TITLE
Tarea 1 Error Descriptivo

### ISSUE THREAD

**Issue by Hernan4444** [IIC2523-2018-2/syllabus#2]
Hola, 
En la tarea ¿a que se refiere con error descriptivo? ¿Indicar por ejemplo que par de base nuclear no concuerda?

Saludos ✌️

**Comment by gpvidal** [comment]
Hola @Hernan4444 !

Por ejemplo:

- "Linea 1 - Columna 3: Composición incorrecta" (Si es que hay una letra que no corresponde)
- "Linea 2 - Columna 5: Secuencia incorrecta AG"

Y así. La idea es que sus mensajes no sean: "Aquí hay un error", sino que detallen un poco más.

Saludos,

**Comment by benjavides** [comment]
Se espera que se detallen todos los errores que hay en una (línea, columna) o basta con especificar uno?

Por ejemplo, si se tiene el siguiente input: "C**RCA**TA**TG** CGCGTATA TAATTAAT ATGCTAAT" cuál de las siguientes versiones se espera?
### versión 1: basta con identificar un tipo de error
Línea 1 - Columna 1: Composición incorrecta, la letra "R" no corresponde.
### versión 2: se deben identificar todos los tipos de errores
Línea 1 - Columna 1: Composición incorrecta, la letra "R" no corresponde.
Línea 1 - Columna 1: Secuencia incorrecta, la secuencia "CA" no es válida.
### versión 3: se deben identificar todos los errores de cada tipo
Línea 1 - Columna 1: Composición incorrecta, la letra "R" no corresponde.
Línea 1 - Columna 1: Secuencia incorrecta, la secuencia "CA" no es válida.
Línea 1 - Columna 1: Secuencia incorrecta, la secuencia "TG" no es válida.

**Comment by gpvidal** [comment]
Hola @benjavides !

La versión 3 :+1: 

Saludos!

**Comment by MortizDX** [comment]
Si un error aparece varias veces en una columna (por ejemplo, solo 'B's), ¿el error sólo debe aparecer una vez para esa columna o debe indicarse cada vez que se encuentra un carácter incorrecto?

**Comment by gpvidal** [comment]
Hola @MortizDX ,

Por simplicidad puedes indicarlo varias veces, pero basta solo una por caracter.

Saludos,

**Comment by MortizDX** [comment]
Disculpa por comentar de nuevo en este thread ya cerrado, pero me surgió una duda particular del tema. Si tengo GTACETSC en una línea, en donde ya hay 2 letras inválidas (E y S) ¿debería considerar ET también como secuencia inválida también (y por lo tanto mostrarlo)? ¿O eso solo se debe revisar con letras válidas?
