### ISSUE TITLE
Tipo de simulación

### ISSUE THREAD

**Issue by PaulaSanzana** [IIC2523-2018-2/syllabus#20]
Tengo una duda existencial, ¿es necesario simular los relojes haciendo que 2 nodos se conecten como cliente y servidor (establecer una conexión abriendo puertos y todo lo demás que implica hacer la conexión) o se puede hacer de manera secuencial (simular el paso del tiempo y su comunicación)?

Asumí que era de la manera secuencial, pero la verdad todavía me queda la duda y me hace estar insegura de lo que llevo de mi tarea :c

Gracias de antemano por la respuesta!

**Comment by gpvidal** [comment]
Hola @PaulaSanzana ,

No es necesario que se comuniquen en cliente servidor,  esta bien que sea de forma sequencial.

Saludos,

**Comment by AlfonsoIgnacioV** [comment]
Hola!
Respecto a eso mismo, me cabe la duda, con secuencial se refieren a que no es necesario hacer que cliente y servidor sean Threads? O sea bastaría usar un while en cada programa para que esto funcione?

Gracias
Saludos

**Comment by gpvidal** [comment]
Hola @AlfonsoIgnacioV ,

Basta con un while, no es necesario que hayan threads y no se requiere cliente servidor.

Saludos,
