### ISSUE TITLE
T03 - NTP, Tiempo preparación respuesta

### ISSUE THREAD

**Issue by benjavides** [IIC2523-2018-2/syllabus#21]
En NTP se debe considerar un tiempo de preparación de respuesta por parte del servidor.
![image](https://user-images.githubusercontent.com/7333792/49037938-4a621680-f19a-11e8-8603-cc28c31b3805.png)
El enunciado no especifica un valor o intervalo.
a) Usamos el mismo intervalo que para el delay de comunicación.
b) Lo consideramos 0.
c) Elegimos lo que queramos, pero lo explicamos en nuestro `README.md`.

**Comment by gpvidal** [comment]
Hola @benjavides ,

No debería ser cero. Opción C para este caso :+1: 

Saludos,

**Comment by aiquinones** [comment]
Hola @gpvidal ,

> No debería ser cero. Opción C para este caso 👍

Y en el algoritmo de Cristian puedo asumir que el tiempo es 0? Así me aparece en distintos ejemplos del algoritmo.

**Comment by gpvidal** [comment]
@Aiquinones , en el caso de Cristian pueden hacerlo, en el basado en NTP no.

Saludos,
