### ISSUE TITLE
[Tarea 3] Sobre el avance de los relojes

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2523-2018-2/syllabus#22]
Hola! No sé si esto lo han preguntado, pero es una duda que me queda... El enunciado habla de que los relojes iniciales deben tener una diferencia, pero creo que nunca se menciona (aunque me parece que es lógico) que cuando transcurre tiempo en la simulación, el reloj cliente (el que debe ajustarse) tiene que avanzar más rápido o más lento. ¿Es necesario implementar eso? He probado de ambas formas. 

A modo de ejemplo, si en el tiempo real transcurren 6 segundos, pero el reloj cliente es más lento, para él pasan sólo 4 segundos (asumiendo que el servidor va bien con el tiempo real y también detecta que pasaron 6 segundos).

No sé si se entiende
Gracias!
Saludos

**Comment by gpvidal** [comment]
Hola @AlfonsoIgnacioV ,

Ambos relojes avanzan a la misma velocidad, un segundo es un segundo en ambos relojes. Por ejemplo:

- Si el reloj 1 tiene el valor 120 y el reloj 2 tiene el valor 255, al pasar 10 segundos, el reloj 1 estará en 130 y el reloj 2 en 265.

Responde eso tu pregunta?

Saludos,

**Comment by AlfonsoIgnacioV** [comment]
Hola @gpvidal !
Sí, me queda claro
Gracias :)
Saludos
