### ISSUE TITLE
Tarea 1: Sobre las secuencias válidas

### ISSUE THREAD

**Issue by MortizDX** [IIC2523-2018-2/syllabus#3]
Buenas, tengo algunas dudas sobre que secuencias son válidas o no, para estar más claro:
1. Como los caracteres se consideran de a pares ¿esta columna "GCCGCGGC" sería válida? Lo pregunto porque si reviso de a dos en dos, "CC" no sería válida por si sola, pero cada 'C' está acompañada por una 'G'.
2. Para ver si comprendí bien, ¿cada columna solo puede tener 2 caracteres distintos, tales que pertenezcan a {A,T} o {C,G}, pero no a la vez? 
3. ¿Debemos preocuparnos si nos entregan archivos con columnas con más de 8 caracteres y lineas con más de 8 columnas?
Saludos,
Mauricio Ortiz

**Comment by farojos** [comment]
1.- Si es válida

2.- No. Si vemos el ejemplo, la primera columna: ATGCCGTA

3.- Puedes suponer que el formato de 8 columnas y 8 letras cada una se cumple siempre. (enunciado)

Saludos

**Comment by MortizDX** [comment]
Gracias por la respuesta!

**Comment by MortizDX** [comment]
Gracias por la respuesta, pero la 2da me sigue dejando en duda, que como el enunciado dice:

> Siempre deben aparecer en pares AT y GC, pueden estar como TA y CG. No pueden mezclarse entre estos pares (ej. GT).

¿Eso quiere decir que no puede estar GT sólo (ejemplo: "GTGTATAT") a menos que G y T estén acompañados como corresponde? (como el ejemplo que dices, "ATGCCGTA")

**Comment by farojos** [comment]
GT|GT|AT|AT es no válido. 
AT|GC|CG|TA es válido.

Espero que eso te oriente. 

Saludos

**Comment by MortizDX** [comment]
Aaah, entonces sólo vamos revisando de a pares, eso no lo tenía claro. Muchas gracias!
