### ISSUE TITLE
Material de la actividad de threads

### ISSUE THREAD

**Issue by MortizDX** [IIC2523-2018-2/syllabus#5]
Buenas, quería consultar sobre la actividad de threads que se vio en clases hace unas semanas, que el link que puso el profesor [http://iic2523.phobos.cl:8000] no me ha funcionado. ¿Acaso era solo para ver ese día o no está activo por estas fechas?

Lo pregunto porque quería verificar si la intención de la tarea era utilizar el modulo threading o multiprocessing.

**Comment by gpvidal** [comment]
Hola @MortizDX !

Para ese ejercicio ocupamos `threading` :+1: 
De todas formas, volví a subir el servidor.

Saludos!
