### ISSUE TITLE
Tarea 1 Parámetro

### ISSUE THREAD

**Issue by PaulaSanzana** [IIC2523-2018-2/syllabus#6]
Hola, 

En la tarea cuando dice que se debe permitir un parámetro para la ruta de archivo, ¿se refiere a pedirlo mediante la línea de comando antes de ejecutar el programa o pedirlo una vez ejecutado el programa?

**Comment by gpvidal** [comment]
Hola @PaulaSanzana !

Lo primero, en la línea de comandos. Algo del tipo:
```
$ python3 my_program.py ./file.txt
```
Saludos!

**Comment by PaulaSanzana** [comment]
Entendido, muchas gracias!
