### ISSUE TITLE
Tarea 1 - Multiprocesamiento y heterogeneidad

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2523-2018-2/syllabus#7]
Hola! Mi duda es la siguiente: en #5 se mencionaba algo acerca de la librería, pero no me quedó muy claro qué librería es la que se espera que usemos, si `Multiprocessing` o `Threading`, o si podemos utilizar ambas. 

Otra duda que tengo es de qué forma podemos saber que la condición de heterogeneidad se cumple. ¿Basta con lo que dice de que no se deberían correr infinitos threads y/o procesos, o eso es un ejemplo y habría que considerar otros aspectos?

Muchas gracias!
Saludos

**Comment by gpvidal** [comment]
Hola @AlfonsoIgnacioV ,

Con respecto a tu primera pregunta, en ningún lado hay restricción de librería. Yo les mostré `threading` en el ejercicio que hicimos en clases, pero en el enunciado no aparece. Debes ser tú quien elija cuál es la que mejor se adapta para resolver el problema. Hay completa libertad en este caso.

Con respecto a tu segunda pregunta, va a depender de la librería que ocupes también, pero uno de los puntos importantes es que no puedas correr infinitos threads.

Saludos,

**Comment by AlfonsoIgnacioV** [comment]
Gracias! Saludos
