### ISSUE TITLE
Tarea 1 - Límite de Ram

### ISSUE THREAD

**Issue by AntoniaMendoza** [IIC2523-2018-2/syllabus#8]
Dado que en clases se mencionó que el programa tenía que ser robusto a archivos de cualquier tamaño,
implicando que en varios casos no se puede guardar todo el archivo en ram, me entró la siguiente duda:

¿Podemos asumir que todos los errores (descriptivos) podrán ser guardados en ram?

**Comment by gpvidal** [comment]
Hola @AntoniaMendoza ,

Depende, pero si podrían suponerlo. Es decir, si tienes un archivo de 10 lineas y los errores ocupan 4GB de RAM eso claramente indica que hay un error. Pero para tamaños razonables sí.

Saludos,
