### ISSUE TITLE
Tarea 1: Mostrar errores de forma incremental

### ISSUE THREAD

**Issue by MortizDX** [IIC2523-2018-2/syllabus#9]
Tengo una duda sobre el enunciado, que al principio se pide mostrar los errores "incrementalmente", y pensé que se refería a mostrar a que línea y columna correspondía el error, aun si otro thread evalua una linea antes que otra (o sea, no necesariamente en el orden en que venían en el archivo). Pero después, en la parte de las preguntas, hablan de liberar la "restricción de orden". En un principio, ¿debemos asegurar que los errores se muestren en orden entonces?

**Comment by gpvidal** [comment]
Hola @MortizDX ,

Sí, efectivamente tiene que ser en orden. Luego se debe quitar esa restricción en la pregunta más abajo.

Saludos,
Gabriel
